name: PR Build

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: latest
      - name: Ballerina Build
        run: bal pack
      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: latest
      - name: Ballerina Test
        run: bal test --test-report --code-coverage --coverage-format=xml
        env:
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          REGION: ${{ secrets.REGION }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
